spring.application.name=nutrismart-platform
spring.profiles.active=dev
spring.jpa.open-in-view=false
spring.jpa.hibernate.naming.physical-strategy=com.devteam.nutrismart.platform.shared.infrastructure.persistence.jpa.strategy.SnakeCasePhysicalNamingStrategy

documentation.application.description=NutriSmart Platform REST API
documentation.application.version=1.0.0
